### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by hello-smile6** [JoshAtticus/Ninetails-homepages#1]
```bash
$ curl https://ninetails-homepages.cf/ask --output -
curl: (60) SSL: no alternative certificate subject name matches target host name 'ninetails-homepages.cf'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by JoshAtticus** [comment]
I have discovered that because of how Freenim works, you must access it over http, not https.

**Comment by hello-smile6** [comment]
> I have discovered that because of how Freenim works, you must access it over http, not https.

Well, that's a definite no. @JoshAtticus I'll hit it with `wget -page-requisites` on Replit and send the link. Or, you could do it yourself. https://replit.com/

**Comment by JoshAtticus** [comment]
I don't have replit, and I have no intrest in signing up

**Comment by JoshAtticus** [comment]
Alternatively, I could setup security in 000webhost, although that'll be $9.99 a month for premium, which is required for SSL, I know right, dumb

**Comment by hello-smile6** [comment]
> I don't have replit, and I have no intrest in signing up

Okay, then I'll hit it, unless you'd be willing to share your code on a GitHub gist. https://gist.github.com/

> Alternatively, I could setup security in 000webhost, although that'll be $9.99 a month for premium, which is required for TLS, I know right, dumb

Don't waste the money. It'd be cheaper to just set the CNAME record to point to a replit repl. I'll get it set up.

**Comment by hello-smile6** [comment]
> Alternatively, I could setup security in 000webhost, although that'll be $9.99 a month for premium, which is required for SSL, I know right, dumb

That service sounds like a scam. But then, most web hosting services do.

**Comment by JoshAtticus** [comment]
> > I don't have replit, and I have no intrest in signing up
> 
> Okay, then I'll hit it, unless you'd be willing to share your code on a GitHub gist. https://gist.github.com/
> 
> > Alternatively, I could setup security in 000webhost, although that'll be $9.99 a month for premium, which is required for TLS, I know right, dumb
> 
> Don't waste the money. It'd be cheaper to just set the CNAME record to point to a replit repl. I'll get it set up.

Freenom doesn't have CNAME options for free domains

**Comment by JoshAtticus** [comment]
> > Alternatively, I could setup security in 000webhost, although that'll be $9.99 a month for premium, which is required for SSL, I know right, dumb
> 
> That service sounds like a scam. But then, most web hosting services do.

They are owned by a popular and trusted service called Hostinger, so I trust them.

**Comment by hello-smile6** [comment]
> > > Alternatively, I could setup security in 000webhost, although that'll be $9.99 a month for premium, which is required for SSL, I know right, dumb
> > 
> > 
> > That service sounds like a scam. But then, most web hosting services do.
> 
> They are owned by a popular and trusted service called Hostinger, so I trust them.

Um, let me guess. They say that they are "trusted" on their website.
Most say otherwise.
https://www.trustpilot.com/review/freenom.com
I'd suggest that you scrap everything and use Google Domains.

**Comment by hello-smile6** [comment]
@JoshAtticus Just abort everything now. It's not worth risking everything.
https://daniel.is-a.dev/blog/freenom-the-free-domains-website-is-a-scam-3

**Comment by JoshAtticus** [comment]
I don't have any money to spend, I'm going to stick with freenom until my domain is revoked.

**Comment by JoshAtticus** [comment]
And I said 000webhost was owned by hostinger, not freenom, I already know about freenom scams

**Comment by hello-smile6** [comment]
> I don't have any money to spend, I'm going to stick with freenom until my domain is revoked.

Can you get them to revoke it? Maybe someone could fund it. Just create a Patreon account and set up the sponsor button to use it. You might get lucky.

**Comment by JoshAtticus** [comment]
> > I don't have any money to spend, I'm going to stick with freenom until my domain is revoked.
> 
> Can you get them to revoke it? Maybe someone could fund it. Just create a Patreon account and set up the sponsor button to use it. You might get lucky.

I am under-age and don't have a way of using the money legally

**Comment by hello-smile6** [comment]
> > > I don't have any money to spend, I'm going to stick with freenom until my domain is revoked.
> > 
> > 
> > Can you get them to revoke it? Maybe someone could fund it. Just create a Patreon account and set up the sponsor button to use it. You might get lucky.
> 
> I am under-age and don't have a way of using the money legally

Oh, maybe you could have @MystPi set up a subdomain of ninetails.cf to point to a server with those files.

**Comment by JoshAtticus** [comment]
> > > > I don't have any money to spend, I'm going to stick with freenom until my domain is revoked.
> > > 
> > > 
> > > Can you get them to revoke it? Maybe someone could fund it. Just create a Patreon account and set up the sponsor button to use it. You might get lucky.
> > 
> > 
> > I am under-age and don't have a way of using the money legally
> 
> Oh, maybe you could have @MystPi set up a subdomain of ninetails.cf to point to a server with those files.

Possibly, what if @MystPi doesn't want to setup a sub-domain, you know ninetails.cf is a freenom domain too right?

**Comment by hello-smile6** [comment]
> > > > > I don't have any money to spend, I'm going to stick with freenom until my domain is revoked.
> > > > 
> > > > 
> > > > Can you get them to revoke it? Maybe someone could fund it. Just create a Patreon account and set up the sponsor button to use it. You might get lucky.
> > > 
> > > 
> > > I am under-age and don't have a way of using the money legally
> > 
> > 
> > Oh, maybe you could have @MystPi set up a subdomain of ninetails.cf to point to a server with those files.
> 
> Possibly, what if @MystPi doesn't want to setup a sub-domain, you know ninetails.cf is a freenom domain too right?

It is?

**Comment by JoshAtticus** [comment]
Yep, @MystPi mentions it here: https://github.com/MystPi/ninetails/issues/57#issuecomment-996693816

**Comment by JoshAtticus** [comment]
Yep, @MystPi mentions it here: https://github.com/MystPi/ninetails/issues/57#issuecomment-996693816

**Comment by hello-smile6** [comment]
> Yep, @MystPi mentions it here: [MystPi/ninetails#57 (comment)](https://github.com/MystPi/ninetails/issues/57#issuecomment-996693816)

Okay, could you put your HTML and everything in this repo?

**Comment by JoshAtticus** [comment]
Also I saw your comment critising my work :( on the ninetails https://github.com/MystPi/ninetails/issues/46#issuecomment-997326922, i'm not removing your comment from my quote, what is done is done

**Comment by hello-smile6** [comment]
> Also I saw your comment critising my work :( on the ninetails [MystPi/ninetails#46 (comment)](https://github.com/MystPi/ninetails/issues/46#issuecomment-997326922), i'm not removing your comment from my quote, what is done is done

Sorry, I misunderstood.

**Comment by JoshAtticus** [comment]
> > Yep, @MystPi mentions it here: [MystPi/ninetails#57 (comment)](https://github.com/MystPi/ninetails/issues/57#issuecomment-996693816)
> 
> Okay, could you put your HTML and everything in this repo?

Uh, sure

**Comment by JoshAtticus** [comment]
> > Also I saw your comment critising my work :( on the ninetails [MystPi/ninetails#46 (comment)](https://github.com/MystPi/ninetails/issues/46#issuecomment-997326922), i'm not removing your comment from my quote, what is done is done
> 
> Sorry, I misunderstood.

It's ok

**Comment by hello-smile6** [comment]
> > > Yep, @MystPi mentions it here: [MystPi/ninetails#57 (comment)](https://github.com/MystPi/ninetails/issues/57#issuecomment-996693816)
> > 
> > 
> > Okay, could you put your HTML and everything in this repo?
> 
> Uh, sure

Thanks, I'd like to run a mirror (using `git clone`) on Replit, just in case some people would like HTTPS for various reasons.

**Comment by JoshAtticus** [comment]
So, they are all in folders, what do I do? I don't know how to upload folders

**Comment by JoshAtticus** [comment]
I can give you access to the 000webhost file manager (temp set a password that you can use)

**Comment by hello-smile6** [comment]
> I can give you access to the 000webhost file manager (temp set a password that you can use)

Okay, does that let you download?

**Comment by JoshAtticus** [comment]
Yes

**Comment by hello-smile6** [comment]
> Yes

Okay. You could also download, rename the .zip to .png , and upload as a comment attachment. GitHub should let you.

**Comment by JoshAtticus** [comment]
Ok

**Comment by JoshAtticus** [comment]
Lol, their file manager doesn't let you bulk download, however it just so happens that their file manager is an FTP client

**Comment by JoshAtticus** [comment]
And I have server and login details

**Comment by hello-smile6** [comment]
> Lol, their file manager doesn't let you bulk download, however it just so happens that their file manager is an FTP client

Can you enable anonymous read-only access?

**Comment by JoshAtticus** [comment]
No

**Comment by hello-smile6** [comment]
Why not?

**Comment by JoshAtticus** [comment]
I get 1 username and password with full access

**Comment by hello-smile6** [comment]
> I get 1 username and password with full access

Oh. Could you just download everything and share it on https://wormhole.app/ ?

**Comment by JoshAtticus** [comment]
Or google drive? I don't want to sign up for more accounts

**Comment by JoshAtticus** [comment]
Ok this is really hard to work with, it keeps crashing

**Comment by JoshAtticus** [comment]
It would be much easier if I do only one search engine, like ddg (my original search engine of choice)

**Comment by hello-smile6** [comment]
> Ok this is really hard to work with, it keeps crashing

Try instant.io instead, then. Neither need accounts.

**Comment by hello-smile6** [comment]
> It would be much easier if I do only one search engine, like ddg (my original search engine of choice)

Do you know of an FTP server that runs on 32-bit linux and has statically linked 32-bit binary releases? If so, https://copy.sh/v86 might work. We could send data via the websocket proxy.

**Comment by JoshAtticus** [comment]
Nope, I don't work with linux that often

**Comment by JoshAtticus** [comment]
When I say things are crashing, the FTP client on windows is crashing and randomly cancelling data transfer halfway though

**Comment by hello-smile6** [comment]
> When I say things are crashing, the FTP client on windows is crashing and randomly cancelling data transfer halfway though

You mean, Microsoft's CLI or a different one? If you're using a gui, execute `%systemroot%\System32\ftp.exe`

**Comment by JoshAtticus** [comment]
> > When I say things are crashing, the FTP client on windows is crashing and randomly cancelling data transfer halfway though
> 
> You mean, Microsoft's CLI or a different one? If you're using a gui, execute `%systemroot%\System32\ftp.exe`

No, the one built into explorer.exe

**Comment by hello-smile6** [comment]
> > > When I say things are crashing, the FTP client on windows is crashing and randomly cancelling data transfer halfway though
> > 
> > 
> > You mean, Microsoft's CLI or a different one? If you're using a gui, execute `%systemroot%\System32\ftp.exe`
> 
> No, the one built into explorer.exe

Try mounting it as a network drive and then copying everything. If something fails, just try again.

**Comment by JoshAtticus** [comment]
> > > > When I say things are crashing, the FTP client on windows is crashing and randomly cancelling data transfer halfway though
> > > 
> > > 
> > > You mean, Microsoft's CLI or a different one? If you're using a gui, execute `%systemroot%\System32\ftp.exe`
> > 
> > 
> > No, the one built into explorer.exe
> 
> Try mounting it as a network drive and then copying everything. If something fails, just try again.

That's what I was doing

**Comment by hello-smile6** [comment]
> > > > > When I say things are crashing, the FTP client on windows is crashing and randomly cancelling data transfer halfway though
> > > > 
> > > > 
> > > > You mean, Microsoft's CLI or a different one? If you're using a gui, execute `%systemroot%\System32\ftp.exe`
> > > 
> > > 
> > > No, the one built into explorer.exe
> > 
> > 
> > Try mounting it as a network drive and then copying everything. If something fails, just try again.
> 
> That's what I was doing

Would you be okay with sharing the server domain name? I have higher throughput, I might be able to get it to download.

**Comment by JoshAtticus** [comment]
Server: ftp://files.000webhost.com
Username: ninetails-homepages
Temp Password: password

**Comment by hello-smile6** [comment]
> Server: ftp://files.000webhost.com Username: ninetails-homepages Temp Password: password

Okay

**Comment by JoshAtticus** [comment]
Please don't screw my site, oh wait I have backups

**Comment by JoshAtticus** [comment]
I marked comments containing the info off-topic to hide them

**Comment by hello-smile6** [comment]
> I marked comments containing the info off-topic to hide them

It won't connect.

**Comment by hello-smile6** [comment]
Downloading!!! Any duplicates I should know about?

**Comment by JoshAtticus** [comment]
They are all the same files, except all of the "index.html" files **DON'T** delete any files or you will have to rewrite the code

**Comment by JoshAtticus** [comment]
Also, once you have the files ready on your server, send me the link to a document containing where the homepages are and I'll ad it to the readme.md file in this repo.

**Comment by hello-smile6** [comment]
> Also, once you have the files ready on your server, send me the link to a document containing where the homepages are and I'll ad it to the readme.md file in this repo.

Okay

**Comment by JoshAtticus** [comment]
How far into the transfer are you? Can I change my password back yet?
It doesn't take this long, It's only 3MB

**Comment by hello-smile6** [comment]
> How far into the transfer are you? Can I change my password back yet? It doesn't take this long, It's only 3MB

You didn't need the password, it turned out. I couldn't get FTP to work, so I used HTTP and manually downloaded each directory.

**Comment by JoshAtticus** [comment]
Oh I see

**Comment by hello-smile6** [comment]
> Oh I see

Also, I didn't even try to write to it. Reading was too confusing as it was, and I only managed to get a few files over FTP (from a web-based emulator, LOL)

**Comment by JoshAtticus** [comment]
Same

**Comment by JoshAtticus** [comment]
Anyways, are you done yet?

**Comment by hello-smile6** [comment]
> Anyways, are you done yet?

Yes. https://ninetails-homepages.9pfs.repl.co/

**Comment by JoshAtticus** [comment]
> > Anyways, are you done yet?
> 
> Yes. https://ninetails-homepages.9pfs.repl.co/

Ok! I'll add that to my readme.md

**Comment by hello-smile6** [comment]
Does it work for you?

**Comment by JoshAtticus** [comment]
![image](https://user-images.githubusercontent.com/72828296/146665586-0e6534a0-285c-4594-86fc-cb621c5e32e3.png)
No

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/72828296/146665586-0e6534a0-285c-4594-86fc-cb621c5e32e3.png) No

Ugh. Also, it looks like you use Microsoft Edge Chromium with the "Use dark theme for web contents" flag enabled. 🙂

**Comment by JoshAtticus** [comment]
> > ![image](https://user-images.githubusercontent.com/72828296/146665586-0e6534a0-285c-4594-86fc-cb621c5e32e3.png) No
> 
> Ugh. Also, it looks like you use Microsoft Edge Chromium with the "Use dark theme for web contents" flag enabled. 🙂
Nope! I use Firefox Nightly with Dark Reader extension

**Comment by hello-smile6** [comment]
> > > ![image](https://user-images.githubusercontent.com/72828296/146665586-0e6534a0-285c-4594-86fc-cb621c5e32e3.png) No
> > 
> > 
> > Ugh. Also, it looks like you use Microsoft Edge Chromium with the "Use dark theme for web contents" flag enabled. 🙂
> > Nope! I use Firefox Nightly with Dark Reader extension

Oh!

**Comment by hello-smile6** [comment]
Are you going to merge #2?

**Comment by JoshAtticus** [comment]
I am stuck with an unresponsive browser so I’m on my iPhone, can’t  do it at the moment, and I have had troubles with github pages, so I’m avoiding it.

**Comment by hello-smile6** [comment]
> I am stuck with an unresponsive browser so I’m on my iPhone, can’t do it at the moment, and I have had troubles with thin pages, so I’m avoiding it.

Try using Android 4 on v86 in fullscreen. https://copy.sh/v86/?profile=android4

**Comment by JoshAtticus** [comment]
> > I am stuck with an unresponsive browser so I’m on my iPhone, can’t do it at the moment, and I have had troubles with thin pages, so I’m avoiding it.
> 
> Try using Android 4 on v86 in fullscreen. https://copy.sh/v86/?profile=android4

The screen is too small for me to see anything

**Comment by hello-smile6** [comment]
> > > I am stuck with an unresponsive browser so I’m on my iPhone, can’t do it at the moment, and I have had troubles with thin pages, so I’m avoiding it.
> > 
> > 
> > Try using Android 4 on v86 in fullscreen. https://copy.sh/v86/?profile=android4
> 
> The screen is too small for me to see anything

On v86?

**Comment by JoshAtticus** [comment]
> > > > I am stuck with an unresponsive browser so I’m on my iPhone, can’t do it at the moment, and I have had troubles with thin pages, so I’m avoiding it.
> > > 
> > > 
> > > Try using Android 4 on v86 in fullscreen. https://copy.sh/v86/?profile=android4
> > 
> > 
> > The screen is too small for me to see anything
> 
> On v86?

It's still an iPhone 6, also I don't want to use Github to host, I just can't work it and It's **MUCH** easier to use 000webhost
